version: '3.8'

services:
  # Сервис разработки
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    networks:
      - museum-network

  # Сервис продакшена
  prod:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - museum-network
    restart: unless-stopped

networks:
  museum-network:
    driver: bridge 